name: Build Image
on:
  workflow_dispatch:
    inputs:
      airconnect_version:
        description: 'AirConnect binary version(without "v" prefix) to build from'
        required: true
jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          file: Dockerfile
          build-args: |
            VERSION=${{ github.event.inputs.airconnect_version }}
          push: true
          tags: seancheung/airupnp:${{ github.event.inputs.airconnect_version }},seancheung/airupnp:latest
